name: CI

on:
  push:
  pull_request:
  workflow_run: 
    workflows: ["Build docs & open PR"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore Develop.sln
      - name: Build
        run: dotnet build Develop.sln --no-restore
      - name: Test
        run: dotnet test Develop.sln --no-build --verbosity normal
